### ISSUE TITLE
Unserialize while restoring session generate php warning

### ISSUE THREAD

**Issue by mihan007** [yiiext/shopping-cart-component#3]
Shopping cart register through 1 way: Registration in the config file.
To stored model attached zii CTimestamp behavior.

Get this after page reload:
![Shopping Cart Restore From Session Bug](https://dl.dropbox.com/u/1999899/shoppingCartBug.png)

Quick bugfix is to add Yii::import('common.lib.Yii.zii.behaviors.*'); to app import before shoppingCart OR to init function of component before restoreFromSession.

**Comment by samdark** [comment]
This one can't be fixed on framework/extension level since `unserialize` doesn't trigger autoload when class you're trying to unserialize isn't loaded yet (at least by default).

Can be fixed on your PHP config level:

```
unserialize_callback_func = 'spl_autoload_call'
```
